/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.13.0+p3-g40b6564e
 *
 * Project: 'triac_motor_ctrl.Debug+PY32F003x8' 
 * Target:  'Debug+PY32F003x8' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "py32f0xx.h"

/* ARM::CMSIS:RTOS2:Keil RTX5&Library@5.9.1 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */


#endif /* RTE_COMPONENTS_H */
