/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.14.1+p9-g859cb6c9
 *
 * Project: 'triac_motor_ctrl.Release+PY32F003x8' 
 * Target:  'Release+PY32F003x8' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "py32f0xx.h"

/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.1 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
#define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */


#endif /* RTE_COMPONENTS_H */
